<?php

/**
 * @file
 */

/**
 * Implements hook_menu()
 */
function test_menu() {

  $items['test'] = array(
    'title' => 'Test menu hook',
    'callback' => 'test_page',
  );

  $items['test_inc'] = array(
    'title' => 'Test inc file param',
    'callback' => 'test_page',
    'file' => 'modules/test/test.pages.inc',
  );

  $items['test_access_bool'] = array(
    'title' => 'Test menu hook',
    'callback' => 'test_page',
    'access' => FALSE,
  );

  $items['test_access_function'] = array(
    'title' => 'Test menu hook',
    'callback' => 'test_page',
    'access' => 'is_admin_test',
  );

  $items['test_args/%/%'] = array(
    'title' => 'Test 2 args',
    'callback' => 'test_page',
  );

  $items['test_args/%/test'] = array(
    'title' => 'Test 1 arg',
    'callback' => 'test_page',
  );

  return $items;
}

/**
 * test page TODO remove me
 */
function test_page($args = NULL) {
  // dsm('args:');
  // dsm($args);
  // dsm(arg(1));
  // dsm(url('<front>'));
  xcms_set_message('foo');
  xcms_set_message('foo2');

  xcms_set_message('error', 'error');
  xcms_set_message('status', 'status');
  xcms_set_message('warning', 'warning');
  xcms_set_message('foo', 'foo');
  // xcms_goto('welcome');
  return lipsum(10);
}

function is_admin_test() {

  return FALSE;
}

function lipsum($count = 1) {
  $output = '';
  for ($i = 1; $i <= $count; $i++) {
    $output .= 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>';
  }
  return $output;
}

