<?php

/**
 * @file
 */

/**
 * Implements hook_init().
 */
function user_init() {
  global $user;
  $user = user_load_by_name(issetor($_COOKIE['name']));
}

/**
 * Implements hook_menu().
 */
function user_menu() {

  $items['user'] = array(
    'title' => 'User account',
    'callback' => 'user_page',
    'file' => 'modules/user/user.pages.inc',
    'access' => TRUE,
  );

  $items['user/login'] = array(
    'title' => 'Login',
    'callback' => 'user_login_page',
    'file' => 'modules/user/user.pages.inc',
    'access' => 'user_is_anonymous',
  );

  $items['user/logout'] = array(
    'callback' => 'user_logout_page',
    'file' => 'modules/user/user.pages.inc',
    'access' => 'user_is_logged_in',
  );

  // TODO - admin only edits other users.
  $items['user/%/edit'] = array(
    'title' => 'Edit account',
    'callback' => 'user_account_page',
    'file' => 'modules/user/user.pages.inc',
    'access' => 'user_is_logged_in',
  );

  $items['admin/user'] = array(
    'title' => 'Users',
    'callback' => 'user_admin_page',
    'file' => 'modules/user/user.admin.inc',
    'access' => 'user_is_admin',
  );

  return $items;
}

/**
 *
 */
function user_logout() {
  setcookie('name', '', strtotime('-1 month'), '/');
  // session_destroy();
}

/**
 *
 */
function user_load_all() {
  global $conf;
  return $conf['users'];
}

/**
 *
 */
function user_load($uid) {
  $users = user_load_all();
  return (object) $users[array_search($uid, array_column($users, 'uid'))];
}

/**
 *
 */
function user_load_by_name($name) {
  $users = user_load_all();
  return (object) $users[array_search($name, array_column($users, 'name'))];
}

/**
 *
 */
function user_authenticate($name, $pass) {
  $account = user_load_by_name($name);
  if ($account->pass == md5($pass)) {
    return TRUE;
  }
}

/**
 *
 */
function user_session($name) {
  // session_start();
  setcookie('name', $name, strtotime('+1 month'), '/');
}

/**
 *
 */
function user_is_logged_in() {
  return isset($_COOKIE['name']);
}

/**
 *
 */
function user_is_anonymous() {
  return !user_is_logged_in();
}

/**
 *
 */
function user_is_admin() {
  global $user;
  if (issetor($user->uid, 0) == 1) {
    return TRUE;
  }
}

