<?php

/**
 * @file
 */

/**
 * Implements hook_menu()
 */
function system_menu() {

  $items['welcome'] = array(
    'title' => 'Welcome',
    'callback' => 'system_welcome_page',
    'file' => 'modules/system/system.pages.inc',
    'access' => TRUE,
  );

  $items['install'] = array(
    'title' => 'install',
    'callback' => 'system_welcome_page',
    'file' => 'modules/system/system.pages.inc',
    'access' => TRUE,
  );

  return $items;
}

