<?php

/**
 * @file
 */

/**
 * Implements hook_init().
 */
function system_init() {
  xcms_add_css('modules/system/system.css');
}

/**
 * Implements hook_menu().
 */
function system_menu() {

  $items['nocontent'] = array(
    'title' => 'Welcome',
    'callback' => 'system_welcome_page',
    'file' => 'modules/system/system.pages.inc',
    'access' => TRUE,
  );

  $items['install'] = array(
    'title' => 'install',
    'callback' => 'system_welcome_page',
    'file' => 'modules/system/system.pages.inc',
    'access' => TRUE,
  );

  return $items;
}

