<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function admin_menu() {

  $items['admin/conf'] = array(
    'title' => 'Configuration',
    'callback' => 'admin_conf_page',
    'file' => 'modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  $items['admin/status'] = array(
    'title' => 'Status',
    'callback' => 'admin_status_page',
    'file' => 'modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  $items['admin/status/phpinfo'] = array(
    'callback' => 'admin_phpinfo_page',
    'file' => 'modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  return $items;
}

/**
 * Implements hook_footer().
 */
function admin_footer() {

  global $user;
  // TODO roles / permissions for admin
  // required permission hooks.
  if (user_is_admin()) {
    xcms_add_css('modules/admin/css/admin.css');

    $admin_items = array(
      'home' => l('Home', ''),
      'conf' => l('Configuration', 'admin/conf'),
      'status' => l('Status', 'admin/status'),
      // 'status' => l('Status', 'admin/status'),
      // 'status' => l('Status', 'admin/status'),
      'user' => l('User', 'user'),
    );

    $links = theme_list(array('items' => $admin_items, 'attributes' => array('class' => 'toolbar-menu')));
    return array('toolbar' => '<div id="toolbar">' . $links . l('Log out', 'user/logout', array('attributes' => array('class' => 'toolbar-logout'))) . '</div>');
  }
}

