<?php

/**
 * @file
 */

/**
 * Implements hook_menu()
 */
function system_menu() {

  $items['install'] = array(
    'title' => 'install',
    'callback' => 'system_welcome_page',
  );

  $items['welcome'] = array(
    'title' => 'Welcome',
    'callback' => 'system_welcome_page',
  );

  $items['test'] = array(
    'title' => 'Test menu hook',
    'callback' => 'test_page',
  );

  $items['test_access_bool'] = array(
    'title' => 'Test menu hook',
    'callback' => 'test_page',
    'access' => FALSE,
  );

  $items['test_access_function'] = array(
    'title' => 'Test menu hook',
    'callback' => 'test_page',
    'access' => 'is_admin_test',
  );

  $items['test_args/%/%'] = array(
    'title' => 'Test 2 args',
    'callback' => 'test_page',
  );

  $items['test_args/%/test'] = array(
    'title' => 'Test 1 arg',
    'callback' => 'test_page',
  );

  return $items;
}

// TODO move to somefile.pages.inc
function system_welcome_page() {
  return 'No front page content has been created yet.';
}

/**
 * test page TODO remove me
 */
function test_page($args = NULL) {
  // dsm('args:');
  // dsm($args);
  // dsm(arg(1));
  dsm(url('<front>'));
  // xcms_goto('welcome');
  return 'hello world';
}

function is_admin_test() {

  return FALSE;
}

