<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function admin_menu() {

  $items['admin/conf'] = array(
    'title' => 'Configuration',
    'callback' => 'admin_conf_page',
    'file' => 'core/modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  $items['admin/status'] = array(
    'title' => 'Status',
    'callback' => 'admin_status_page',
    'file' => 'core/modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  $items['admin/status/phpinfo'] = array(
    'callback' => 'admin_phpinfo_page',
    'file' => 'core/modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  return $items;
}

/**
 * Implements hook_footer().
 */
function admin_footer() {
  if (user_is_admin()) {
    xcms_add_css('core/modules/admin/admin.toolbar.css');

    // Load top level admin items for menu.
    global $_menu;
    $admin_items = array('home' => l('Home', ''));
    foreach ($_menu as $path => $item) {
      if (arg(0, $path) == 'admin' && empty(arg(2, $path))) {
        $admin_items[] = l($item['title'], $path);
      }
    }
    $links = theme_list(array('items' => $admin_items, 'attributes' => array('class' => 'toolbar-menu')));

    return array('toolbar' => '<div id="toolbar">' . $links . l('Log out', 'user/logout', array('attributes' => array('class' => 'toolbar-logout'))) . '</div>');
  }
}

