<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function admin_menu() {

  $items['admin/config'] = array(
    'title' => 'Configuration',
    'callback' => 'admin_overview_page',
    'file' => 'core/modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  $items['admin/config/settings'] = array(
    'title' => 'Settings',
    'callback' => 'admin_settings_page',
    'file' => 'core/modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  $items['admin/config/cache'] = array(
    'title' => 'Flush Cache',
    'callback' => 'admin_cache_page',
    'file' => 'core/modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  $items['admin/status'] = array(
    'title' => 'Status',
    'callback' => 'admin_status_page',
    'file' => 'core/modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  $items['admin/status/phpinfo'] = array(
    'callback' => 'admin_phpinfo_page',
    'file' => 'core/modules/admin/admin.admin.inc',
    'access' => 'user_is_admin',
  );

  return $items;
}

/**
 * Implements hook_footer().
 */
function admin_footer() {
  if (user_is_admin()) {
    xcms_add_css('core/modules/admin/admin.toolbar.css');

    // Load top level admin items for menu.
    global $_menu;

    // Add home link to menu
    $admin_items = array(
      'home' => array(
        'title' => 'Home',
        'href' => '<front>',
      ),
    );

    foreach ($_menu as $path => $item) {
      $arg_0 = arg(0, $path);
      $arg_2 = arg(2, $path);
      if ($arg_0 == 'admin' && empty($arg_2)) {
        $admin_items[strip_class($path)] = array(
          'title' => $item['title'],
          'href' => $path,
        );
      }
    }
    $links = theme('links', array('links' => $admin_items, array('attributes' => array('class' => 'toolbar-menu'))));
    return array('toolbar' => '<div id="toolbar">' . $links . l('Log out', 'user/logout', array('attributes' => array('class' => 'toolbar-logout'))) . '</div>');
  }
}

